job:
  type: eval
  device: cuda:0
  auto_correct: true

dataset:
  name: fb15k-237

import:
  - rotate
  - reciprocal_relations_model

model: reciprocal_relations_model

lookup_embedder:
  dim: 256

reciprocal_relations_model:
  base_model:
    relation_embedder:
      dim: 128
    type: rotate

eval:
  type: entity_ranking
  split: test
  batch_size: 256

entity_ranking:
  chunk_size: 5000
  hits_at_k_s: [1, 3, 10]
  metrics_per:
    relation_type: false
    head_and_tail: false
    argument_frequency: false

valid:
  metric: mean_reciprocal_rank_filtered_with_test
